spring.config.import=file:env.properties

spring.application.name=invoice-dashboard

# db connection
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_DATABASE}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# port
server.port=8080
logging.level.root=INFO

# swagger
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

# open-in-view
spring.jpa.open-in-view=false